[goldmark]
  [goldmark.renderer]
    unsafe = true
  [goldmark.extensions]
    typographer = false
  [goldmark.extensions.passthrough]
    enable = true
  [goldmark.extensions.passthrough.delimiters]
    block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
    inline = [ [ "\\(", "\\)" ] ]
[highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  style = "monokai"
  tabWidth = 2
[tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2
