description = "a lighting shell"
externalLinkDecoration = true

displayUpdatedDate = true
dateFormat = "2006年1月2日"

# customCSS = ["/css/c.css"]

# use the setting below to set multiple docs directories.
# docSections = ["glance"]

# uniqueHomePage = true # change to false to add sidebar to homepage

# blogDir = "blog" # can be posts, blog e.t.c

# repo = "https://codeberg.org/santo/lumesh"

# time_format_blog = "Monday, January 02, 2006"
# time_format_default = "January 2, 2006"
# enableDarkMode = false                        # set to false to disable darkmode by default # user will still have the option to use dark mode
# defaultLightingMode = "auto"                  # other possible values: "dark", "light"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
# codeMaxLines = 30

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
# showLineNumbers = true

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

# otherSearchableFields = [
#   "Tags",
#   "Categories",
#   "CustomField",
# ] # As they appear in frontmatter

# Defaults to true if not set
# Enable copyRight Footer Stamp. Takes in attribution
enableCopyright = true

# search

[search]
enable = true
type = "flexsearch"

  [search.flexsearch]
  index = "content"

# Site logo
# [logo]
# lightMode = "/images/logo.svg"
# darkMode = "/images/logo.svg"

# [source]
# name = "GitHub"
# iconLight = "/images/github.png"
# iconDark = "/images/github.png"
# url = "https://github.com/superiums/lumesh/"

# optional
# attribution. Feel free to delete this
[author]
name = "Santo"
url = "https://lumesh.codeberg.page/"

[navbar]
displayTitle = true
displayLogo = true

  [navbar.logo]
  path = "images/logo.svg"
  dark = "images/logo-dark.svg"
  link = "/"
  width = 40
  height = 20

[theme]
default = "system"
displayToggle = true

[blog]
  [blog.list]
  displayTags = true

[toc]
displayTags = true

[footer]
enable = true
displayCopyright = true
displayPoweredBy = true
width = "normal"

[page]
width = "normal"
